ExpressAI/DataLab

datasets/duorc/duorc.py
datasets/hotpot_qa/hotpot_qa.py
datasets/spider/spider.py
datasets/wiki_hop/wiki_hop.py
src/datalabs/tasks/__init__.py
src/datalabs/tasks/question_answering.py
src/datalabs/tasks/semantic_parsing.py
src/datalabs/tasks/sql_generation.py

add three qa datasets (hotpot, duorc, wiki_hop) and one sql generation dataset (spider)

Add qa datasets

---

datasets/race/race.py
src/datalabs/tasks/__init__.py
src/datalabs/tasks/question_answering.py

add race dataset

---

datasets/natural_questions/natural_questions.py
src/datalabs/tasks/__init__.py
src/datalabs/tasks/question_answering.py

Add natural_questions

---

datasets/metaphor_qa/metaphor_qa.py

I added a description, unfortunately it has no citation yet since the paper was just submitted 😅 I will add a citation after it's published

Add metaphor-qa dataset

---

src/datalabs/arrow_dataset.py
tests/arrow_dataset/test_multi.py

There are two probable path to achieve and it was written in `apply_memory` and `apply_local` separately.

Add multiprocessing in `apply`

---

datasets/mlqa/mlqa.py
datasets/xquad/xquad.py

add multilingual qa: xquad, mlqa

add multilingual qa: xquad, mlqa

---

src/datalabs/builder.py
src/datalabs/load.py

No need to change loader script;

Add loading in multiprocessing

---

datasets/cnewsum/cnewsum.py

```
{"article": ["今天 凌晨两点 左右 , 在 惠安县 辋川 农贸市场 边 的 世纪 商业城 一 楼层 套房 发生 火灾 , 火 借 风 势 迅速 燃烧 起来 , 赶到 的 消防 官兵 立即 进行 了 扑救 。", "本 以为 这 是 一起 普通 的 火灾 , 没想到 , 火 熄灭 后 , 大家 突然 发现 现场 有 一个 人 躺在 地上 , 浑身 是 血 …", "深夜 , 辋川 农贸市场 边 的 世纪 商业城 的 人 们 在 熟睡中 听到 三楼 的 一套 房 内 传出 阵阵 惨叫声 , 大家 从 窗口 一看 , 只见 邻居家 的 阳台 浓烟 滚滚 , 火 从 防盗网 窜出 , 大家 赶紧 拨打 119 电话 报警 。", "惠安 消防 一 中队 的 官兵 赶到 后 , 迅速 架起 水枪 灭火 , 经过 近 半小时 的 扑救 , 大火 终于 被 扑灭 。", "这时 , 大家 才 看清 地上 居然 还 躺着 一个 血淋淋 的 人 , 脖子 、 胸前 、 手臂 、 背部 有 多 处 伤口 , 肠子 从 肚子 里 流 了 出来 , 大家 赶忙 叫来 120 急救车 将 他 送往 惠安县 医院 抢救 。", "一起 火灾 , 现场 怎么 会 有 一个 浑身 刀伤 , 血淋淋 的 人 呢 ?", "难道 另有 隐情 ?", "经过 消防 官兵 初步 调查 , 这 起 火灾 并非 天灾 而是 人祸 , 是 房子 的 主人 故意 纵火 的 。", "据 目击者 说 , 火 是 房主 自己 放 的 。", "当时 , 他们 听到 房主 和 他 的 儿子 两人 正在 吵架 , 房主 在 神志不清 的 情况下 纵火 。", "火烧 起来 , 他们 急忙 跑出去 询问 , 房主 却说 : “ 没 你们 什么事 , 你们 去 睡觉 。", "大家 都 不敢吭声 , 只好 …
```

Add CNewSum Chinese summarization dataset

---

datasets/csds/csds.py

```
Python 3.8.12 (default, Oct 12 2021, 06:23:56)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from datalabs import load_dataset
>>> dataset = load_dataset("**/Github/DataLab/datasets/csds")
WARNING:datalabs.builder:No config specified, defaulting to: csds_dataset/document
Downloading and preparing dataset csds_dataset/document to **/.cache/expressai/datalab/csds_dataset/document/1.0.0/d917e72cab92a2b631f5495349367fcf2d90d11643ad013711f273f9534a2790...
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████| 61.7M/61.7M [00:22<00:00, 2.70MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████| 5.40M/5.40M [00:01<00:00, …
```

Update CSDS: Chinese Dataset for Customer Service Dialogue Summarization

---

datasets/ssn/ssn.py
docs/WebUI/10_analyzing_summarization_datasets.md

```
dataset = load_dataset("ssn")
print(dataset['test']._info)
print(dataset['test']._info.task_templates)
print(dataset["test"]["text"][5])
print(dataset["test"]["summary"][5])
"""
DatasetInfo(description='we construct a novel scientific papers summarization dataset Semantic Scholar Network (SSN)\nwhich contains 141K research papers in different domains and 661K citation relationships. \nThe entire dataset constitutes a large connected citation graph.\nWe divide the enhanced summarization task into 2 settings: \n(1) transductive: during training, models can access to all the nodes and edges in the\nwhole dataset including papers (excluding abstracts) in the test set. \n(2) inductive: papers in the test set are from a totally new graph\nwhich means all test nodes cannot be used during …
```

Update SSN dataset

---

datasets/gazeta/gazeta.py
datasets/pn_summary/pn_summary.py
datasets/scitldr/scitldr.py
docs/WebUI/10_analyzing_summarization_datasets.md

```python
dataset = load_dataset("pn_summary")
print(dataset['test']._info)
print(dataset['test']._info.task_templates)
print(dataset["test"]["text"][5])
print(dataset["test"]["summary"][5])
DatasetInfo(description='A well-structured summarization dataset for the Persian language consists of 93,207 records. \nIt is prepared for Abstractive/Extractive tasks (like cnn_dailymail for English). \nIt can also be used in other scopes like Text Generation, Title Generation, \nand News Category Classification. Moreover, we tested out this dataset on novel models and techniques.\nsee: https://arxiv.org/pdf/2012.11204.pdf\n', citation='@article{pnSummary,\n  title={Leveraging ParsBERT and Pretrained mT5 for Persian Abstractive Text Summarization},\n  author={Mehrdad Farahani and Mohammad …
```

Update three summarization datasets

---

datasets/metaphor_qa/metaphor_qa.py
docs/SDK/add_new_datasets_into_sdk.md
setup.py
src/datalabs/utils/download_manager.py
src/datalabs/utils/private_utils.py

This adds the ability to get private data from a private data repository or URL. I think the PR should be self-explanatory, but happy to discuss.

Private data utils

---

datasets/iwslt2017/iwslt2017.py

This adds the IWSLT 2017 translation dataset to DataLab by modifying the HF code.

Added iwslt2017 to datalab

---

datasets/fig_qa/fig_qa.py
utils/datasets_info.json

This is simple so I'll just merge it myself.

Fix some more things with figqa

---

datasets/waimai/waimai.py

put the waimai.csv on Aliyun and update the URL in this script.

modify the URL

---

datasets/masakhaner/masakhaner.py

A dataset for named entity recognition in African languages
https://github.com/masakhane-io/masakhane-ner

Add MasakhaNER dataset

---

datasets/amasum/amasum.py
datasets/ami/ami.py
datasets/citesum/citesum.py
datasets/crosssum/crosssum.py
datasets/icsi/icsi.py
datasets/klexikon/klexikon.py
datasets/streamhover/streamhover.py
datasets/welsh/welsh.py
datasets/wsd/wsd.py
docs/WebUI/10_analyzing_summarization_datasets.md

```
dataset = load_dataset("amasum", "pros-ref")
print(dataset['test']._info)
print(dataset['test']._info.task_templates)
print(dataset["test"]["texts"][5])
print(dataset["test"]["summary"][5])
"""
DatasetInfo(description='We collect a large dataset of summaries paired with user reviews for over 31,000 products.\nsee: https://aclanthology.org/2021.emnlp-main.743.pdf\n', citation='@inproceedings{brazinskas-etal-2021-learning,\n    title = "Learning Opinion Summarizers by Selecting Informative Reviews",\n    author = "Bra{\x0b{z}}inskas, Arthur  and\n      Lapata, Mirella  and\n      Titov, Ivan",\n    booktitle = "Proceedings of the 2021 Conference on Empirical Methods in Natural Language Processing",\n    month = nov,\n    year = "2021",\n    address = "Online and Punta Cana, Dominican …
```

Update 9 Summarization Datasets

---

datasets/sdqa/sdqa.py

I added the script for sdqa: a spoken dialectal question answering dataset built to perform dialect level extractive qa task.

Added SDQA dataset

---

.gitignore
datalabs/commands/datasets_cli.py
datalabs/tasks/base.py
datalabs/tasks/text_classification.py
datasets/codeswitch_bangor/codeswitch_bangor.py

Just made some edits
* the file name usually should be consistent with the folder name
* replace the task type of sentiment-classification of codeswitch-identification

update the task type

---

datalabs/tasks/base.py
datalabs/tasks/summarization.py
datasets/answersumm/answersumm.py
datasets/citesum/citesum.py
datasets/mediasum/mediasum.py
datasets/shortstories/shortstories.py
datasets/sumpubmed/sumpubmed.py
datasets/tweetsum/tweetsum.py
datasets/vt-ssum/vt-ssum.py
datasets/wikicite/wikicite.py
docs/WebUI/10_analyzing_summarization_datasets.md

```python
dataset = load_dataset("mediasum", "dialogue")
print(dataset['test']._info)
print(dataset['test']._info.task_templates)
print(dataset["test"]["dialogue"][5])
print(dataset["test"]["summary"][5])
"""
DatasetInfo(description='\nMediaSum is a large-scale media interview dataset contains 463.6K transcripts with abstractive summaries, \ncollected from interview transcripts and overview / topic descriptions from NPR and CNN.\nWe obtain this dataset from https://huggingface.co/datasets/ccdv/mediasum.\nSee: https://aclanthology.org/2021.naacl-main.474.pdf\n', citation='@inproceedings{zhu-etal-2021-mediasum,\n    title = "{M}edia{S}um: A Large-scale Media Interview Dataset for Dialogue Summarization",\n    author = "Zhu, Chenguang  and\n      Liu, Yang  and\n      Mei, Jie  and\n …
```

Update 7 Summarization Datasets

---

datasets/sumeval_2022/sumeval_2022.py
setup.py

I tried to use sumeval in ExplainaBoard and ran into a few issues. Apologies in advance, but I'm going to merge this w/o review because I need to test it out ASAP and AFAIK there's no easy way to test w/ explainaboard_web unless it's merged into the public repo.

Fix a few things for sumeval

---

datasets/flores/flores.py

Dataset loading script for flores-200....modified from huggingface dataset loading script

flores dataset added

---

datalabs/info.py
datalabs/tasks/__init__.py

I was debugging an error that resulted from my local environment, and in doing so added slightly more comprehensive error checking for task templates.

Adds slightly stronger error checking for task templates

---

datasets/gaokao2018_np1/gaokao2018_np1.py
datasets/gaokao2018_np3/gaokao2018_np3.py
datasets/gaokao2019_np1/gaokao2019_np1.py
datasets/gaokao2019_np2/gaokao2019_np2.py
datasets/gaokao2019_np3/gaokao2019_np3.py
datasets/gaokao2020_np1/gaokao2020_np1.py
datasets/gaokao2020_np2/gaokao2020_np2.py
datasets/gaokao2020_np3/gaokao2020_np3.py
datasets/gaokao2021_npa/gaokao2021_npa.py
datasets/gaokao2021_npb/gaokao2021_npb.py

Simple fix of gaokao "answer" column to "answers"

Fix ID in Gaokao column definitions

---

datasets/cmu_anlp/cmu_anlp.py

Add Scientific NER task for CMU ANLP.

Add CMU ANLP sciner
